module.exports = [
    {
      id: 637133,
      image: 'https://spoonacular.com/recipeImages/637133-312x231.jpg',
      title: 'Carne Asada Burritos',
      time: 45,
      missingIngredients: 14,
      likes: 1,
      vegan: false,
      vegetarian: false,
      glutenFree: false,
      dairyFree: true,
      servings: 6,
      summary: "The recipe Carne Asada Burritos can be made in about around 45 minutes. This recipe makes 6 servings with 432 calories, 31g of protein, and 16g of fat each. For $2.83 per serving, this recipe covers 28% of your daily requirements of vitamins and minerals. Only a few people really liked this main course. 1 person has made this recipe and would make it again. A mixture of kosher salt, onion, ground cumin, and a handful of other ingredients are all it takes to make this recipe so delicious. It is a budget friendly recipe for fans of Latin American food. It is brought to you by Foodista. It is a good option if you're following a dairy free diet. All things considered, we decided this recipe deserves a spoonacular score of 76%. This score is solid. Crock Pot Carne Asada for Burritos, Carne Asada, and Carne Asada are very similar to this recipe.",
      instructions: [ [Object] ],
      sourceName: 'Foodista'
    },
    {
      id: 648439,
      image: 'https://spoonacular.com/recipeImages/648439-312x231.jpg',
      title: "Jamie's Guacamole",
      time: 45,
      missingIngredients: 2,
      likes: 1,
      vegan: true,
      vegetarian: true,
      glutenFree: true,
      dairyFree: true,
      servings: 4,
      summary: "Jamie's Guacamole might be a good recipe to expand your hor d'oeuvre recipe box. This recipe serves 4 and costs 44 cents per serving. Watching your figure? This gluten free, dairy free, paleolithic, and lacto ovo vegetarian recipe has 87 calories, 1g of protein, and 7g of fat per serving. This recipe is typical of Mexican cuisine. It is brought to you by Foodista. A mixture of avocado, onion, salt and pepper, and a handful of other ingredients are all it takes to make this recipe so yummy. 1 person were impressed by this recipe. From preparation to the plate, this recipe takes approximately approximately 45 minutes. Taking all factors into account, this recipe earns a spoonacular score of 55%, which is good. guacamole , how to make guacamole | mexican guacamole, Chipotle Mexican Grill Guacamole – freshly made guacamole that is easy to make can be had with this, and Fried Green Plantain with Guacamole and Shrimp (Tostada de Plátano con Camarones y Guacamole) are very similar to this recipe.",
      instructions: [ [Object] ],
      sourceName: 'Foodista'
    },
    {
      id: 633120,
      image: 'https://spoonacular.com/recipeImages/633120-312x231.jpg',
      title: 'Avocado and Cannellini Bean Salad',
      time: 45,
      missingIngredients: 3,
      likes: 1,
      vegan: true,
      vegetarian: true,
      glutenFree: true,
      dairyFree: true,
      servings: 1,
      summary: "Avocado and Cannellini Bean Salad might be just the side dish you are searching for. One serving contains 453 calories, 8g of protein, and 38g of fat. This recipe serves 1 and costs $3.34 per serving. Not a lot of people made this recipe, and 1 would say it hit the spot. Head to the store and pick up grape tomatoes, seasoning, balsamic vinaigrette, and a few other things to make it today. From preparation to the plate, this recipe takes roughly 45 minutes. It is a good option if you're following a gluten free and vegan diet. All things considered, we decided this recipe deserves a spoonacular score of 93%. This score is tremendous. Try Cannellini Bean Salad, Broccoli-and-Cannellini Bean Salad, and Cannellini-and-Green Bean Salad for similar recipes.",
      instructions: [ [Object] ],
      sourceName: 'Foodista'
    },
    {
      id: 633119,
      image: 'https://spoonacular.com/recipeImages/633119-312x231.jpg',
      title: 'Avocado & Tomato Salad Topped with Grilled Shrimp',
      time: 45,
      missingIngredients: 5,
      likes: 1,
      vegan: false,
      vegetarian: false,
      glutenFree: true,
      dairyFree: true,
      servings: 2,
      summary: "Avocado & Tomato Salad Topped with Grilled Shrimp might be just the main course you are searching for. This recipe serves 2 and costs $9.75 per serving. One serving contains 555 calories, 96g of protein, and 7g of fat. It is a good option if you're following a gluten free, dairy free, and pescatarian diet. If you have plum tomatoes, limes, garlic powder, and a few other ingredients on hand, you can make it. This recipe is liked by 1 foodies and cooks. The Fourth Of July will be even more special with this recipe. From preparation to the plate, this recipe takes roughly 45 minutes. All things considered, we decided this recipe deserves a spoonacular score of 83%. This score is spectacular. Try Cherry Tomato, Asparagus, and Avocado Salad Topped with Basil and Feta, Mixed Bean Salad with Avocado, Shrimp and Tomato, and Grilled Shrimp Salad with Corn and Avocado for similar recipes.",
      instructions: [ [Object] ],
      sourceName: 'Foodista'
    },
    {
      id: 633132,
      image: 'https://spoonacular.com/recipeImages/633132-312x231.jpg',
      title: 'Avocado Chicken Salad',
      time: 45,
      missingIngredients: 5,
      likes: 22,
      vegan: false,
      vegetarian: false,
      glutenFree: true,
      dairyFree: true,
      servings: 2,
      summary: "Avocado Chicken Salad might be just the main course you are searching for. This recipe makes 2 servings with 684 calories, 21g of protein, and 60g of fat each. For $3.57 per serving, this recipe covers 30% of your daily requirements of vitamins and minerals. 21 person were impressed by this recipe. From preparation to the plate, this recipe takes around 45 minutes. It is a good option if you're following a gluten free, dairy free, and whole 30 diet. Head to the store and pick up avocados, mayonnaise, extra virgin olive oil, and a few other things to make it today. To use up the limes you could follow this main course with the Watermelon Granita as a dessert. All things considered, we decided this recipe deserves a spoonacular score of 90%. This score is outstanding. Similar recipes include Avocado Chicken Salad, Avocado Chicken Salad, and Chicken Avocado Salad.",
      instructions: [ [Object] ],
      sourceName: 'Foodista'
    },
    {
      id: 651707,
      image: 'https://spoonacular.com/recipeImages/651707-312x231.jpg',
      title: 'Mexican Stuffed Potatoes',
      time: 45,
      missingIngredients: 5,
      likes: 1,
      vegan: false,
      vegetarian: false,
      glutenFree: true,
      dairyFree: false,
      servings: 4,
      summary: "You can never have too many Mexican recipes, so give Mexican Stuffed Potatoes a try. For $2.08 per serving, this recipe covers 25% of your daily requirements of vitamins and minerals. One serving contains 289 calories, 22g of protein, and 10g of fat. This recipe serves 4. It works well as a side dish. This recipe is liked by 1 foodies and cooks. Head to the store and pick up green onion, salsa, cream, and a few other things to make it today. It is brought to you by Foodista. It is a good option if you're following a gluten free diet. From preparation to the plate, this recipe takes approximately approximately 45 minutes. With a spoonacular score of 69%, this dish is solid. Try Mexican Stuffed Sweet Potatoes, Super-Stuffed Mexican Potatoes, and 5 Ingredient Mexican Stuffed Sweet Potatoes for similar recipes.",
      instructions: [ [Object] ],
      sourceName: 'Foodista'
    },
    {
      id: 649343,
      image: 'https://spoonacular.com/recipeImages/649343-312x231.jpg',
      title: 'Layered Chicken Salad With Couscous',
      time: 45,
      missingIngredients: 7,
      likes: 1,
      vegan: false,
      vegetarian: false,
      glutenFree: false,
      dairyFree: true,
      servings: 4,
      summary: 'Need a dairy free main course? Layered Chicken Salad With Couscous could be a great recipe to try. One serving contains 432 calories, 42g of protein, and 15g of fat. For $3.6 per serving, this recipe covers 26% of your daily requirements of vitamins and minerals. 1 person has made this recipe and would make it again. From preparation to the plate, this recipe takes roughly 45 minutes. A mixture of avocado, parsley, cucumber, and a handful of other ingredients are all it takes to make this recipe so delicious. To use up the couscous you could follow this main course with the Couscous Mango Mousse as a dessert. All things considered, we decided this recipe deserves a spoonacular score of 75%. This score is solid. Try Layered Chicken Salad, Layered Chicken Salad, and Summer Layered Chicken Salad for similar recipes.',
      instructions: [ [Object] ],
      sourceName: 'Foodista'
    },
    {
      id: 679509,
      image: 'https://spoonacular.com/recipeImages/679509-312x231.jpg',
      title: 'Not Your Normal Seven Layer Dip',
      time: 15,
      missingIngredients: 7,
      likes: 0,
      vegan: false,
      vegetarian: true,
      glutenFree: true,
      dairyFree: false,
      servings: 12,
      summary: "Not Your Normal Seven Layer Dip might be just the hor d'oeuvre you are searching for. For 70 cents per serving, this recipe covers 5% of your daily requirements of vitamins and minerals. This recipe makes 12 servings with 145 calories, 6g of protein, and 5g of fat each. It is a good option if you're following a gluten free diet. 1 person were impressed by this recipe. A mixture of avocado, refried beans, cilantro flakes, and a handful of other ingredients are all it takes to make this recipe so scrumptious. The Super Bowl will be even more special with this recipe. From preparation to the plate, this recipe takes around 15 minutes. All things considered, we decided this recipe deserves a spoonacular score of 33%. This score is not so awesome. Try Indian 7 Layer Dip, Nacho Normal Cheesecake, and Not a Normal but an Actually Yummy Cheese Ball for similar recipes.",
      instructions: [ [Object] ],
      sourceName: 'Pink When'
    }
  ];